# Generated by Django 5.0.4 on 2024-05-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_workout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
